### ISSUE TITLE
Clone on Windows OS fails because of backslashes in filename

### ISSUE THREAD

**Issue by wbachnik** [jasongilman/proto-repl-demo#13]
Potential usability problem for Windows users (poor souls). Attempt to clone on Windows 10 using git bash ends like that:
```
$ git clone git@github.com:jasongilman/proto-repl-demo.git
Cloning into 'proto-repl-demo'...
remote: Counting objects: 149, done.
Receiving objects:  37% (56/149)   0 (delta 0), pack-reReceiving objects:  36% (54/149)   used 149
Receiving objects: 100% (149/149), 25.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (66/66), done.
Checking connectivity... done.
error: unable to create file file\ with\slashes_in_name.clj (No such file or directory)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Maybe it would be good idea to generate the `file\ with\slashes_in_name.clj` file using a script when testing handling of filenames with backslashes is needed on OSes that should support it?

**Comment by wbachnik** [comment]
Just noticed it's a duplicate of #10. But since there was no discussion there, I'm leaving that open.

**Comment by jasongilman** [comment]
I deleted the file. See if that resolves the issue for you.

**Comment by wbachnik** [comment]
Yep, it works fine now. Thanks!
