### ISSUE TITLE
Run selected tests fail

### ISSUE THREAD

**Issue by maacl** [jasongilman/proto-repl-demo#2]
If I follow the instructions an select a test name and try to run it using `C-, t` I get the following error:

`=> CompilerException java.lang.RuntimeException: Unable to resolve var: subtract-numbers-test in this context, compiling:(/tmp/form-init6780976928482547280.clj:1:1)`

If I run all tests first using using `C-, a 0` the test runs correctly using `C-, t`.

I am using:

proto-repl 0.15.1
ATOM 1.4.1

and 

Leiningen 2.5.3 on Java 1.8.0_45-internal OpenJDK 64-Bit Server VM

on Ubuntu.

**Comment by jasongilman** [comment]
I'm moving this issue to the proto-repl project.
